### ISSUE TITLE
Set up Invoke-Environment as alias in $profile?

### ISSUE THREAD

**Issue by gc435** [nightroman/PowerShelf#1]
I'd like to set up an alias to `Invoke-Environment` in my `$profile`.  I've tried this:

``` PowerShell
New-Alias vsprep c:\Users\me\Documents\WindowsPowerShell\Invoke-Environment.ps1 '"%VS120COMNTOOLS%\vsvars32.bat"'
```

However, I get an error saying `New-Alias : A positional parameter cannot be found that accepts argument '"%VS120COMNTOOLS%\vsvars32.bat"'`.

Any ideas?

**Comment by nightroman** [comment]
PowerShell aliases are very simple, they just give other names, that's it. You cannot define an alias for a command with particular parameters.

But you can define a function in your profile:

```
function vsprep {
    c:\Users\me\Documents\WindowsPowerShell\Invoke-Environment.ps1 '"%VS120COMNTOOLS%\vsvars32.bat"'
}
```

The new command `vsprep` does what you need. It's not an alias but you still only have to type `vsprep`.

**Comment by gc435** [comment]
Thanks.  I knew that at one point in my life, but had forgotten.
